version: '3'

services:
  test:
    image: image:latest
    container_name: template
    env_file:
      - ../.env
    networks:
      - template
    volumes:
      - ../:/usr/src/app
    tty: true
    ports:
      - '${PORT}:${PORT}'

networks:
  template:
    driver: bridge
